<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>8.0.1.2</Version>
    <AssemblyVersion>8.0.1.2</AssemblyVersion>
    <FileVersion>8.0.1.2</FileVersion>
    <InformationalVersion>Pulse Linux 8.0.1.2AE</InformationalVersion>
    <Product>Pulse Supernova Linux</Product>
    <Company>Pulse Platform</Company>
  </PropertyGroup>
</Project>
