<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>pulse-platform</AssemblyName>
    <RootNamespace>Pulse.Platform.Linux</RootNamespace>
    <Product>Pulse Supernova Linux</Product>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
</Project>
